"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Sparkles, X } from "lucide-react";
import { useSyncExternalStore } from "react";

const DISMISS_KEY = "contexthub.beta-banner.dismissed";

/**
 * localStorage as an external store.
 *
 * Reading it in an effect and calling setState would work, but it is a
 * cascading render the linter rightly flags. useSyncExternalStore is the
 * intended tool: the server snapshot reports "dismissed" so the banner is
 * absent from the HTML, then the client snapshot takes over on hydration and
 * the banner animates in. Nothing ever flashes and then disappears.
 */
const listeners = new Set<() => void>();

function subscribe(onChange: () => void) {
  listeners.add(onChange);
  return () => {
    listeners.delete(onChange);
  };
}

function isDismissed() {
  try {
    return localStorage.getItem(DISMISS_KEY) === "1";
  } catch {
    // Private mode or blocked storage. Showing the notice is the safe default.
    return false;
  }
}

/** Nothing to read while rendering on the server, so assume dismissed. */
function isDismissedOnServer() {
  return true;
}

function dismiss() {
  try {
    localStorage.setItem(DISMISS_KEY, "1");
  } catch {
    // Nothing to do. It reappears next load, which is acceptable.
  }
  for (const listener of listeners) listener();
}

/**
 * One line at the top of the app saying this is a beta.
 *
 * Dismissal lives in localStorage rather than on the user record, because the
 * point is to set expectations once per browser, not to become a per account
 * setting the backend has to store and sync.
 */
export function BetaBanner() {
  const dismissed = useSyncExternalStore(subscribe, isDismissed, isDismissedOnServer);

  return (
    <AnimatePresence initial={false}>
      {!dismissed && (
        <motion.div
          initial={{ height: 0, opacity: 0 }}
          animate={{ height: "auto", opacity: 1 }}
          exit={{ height: 0, opacity: 0 }}
          transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
          className="relative shrink-0 overflow-hidden bg-gradient-brand text-white"
        >
          <div className="flex items-center justify-center gap-2.5 px-10 py-1.5 text-center">
            <Sparkles className="hidden h-3.5 w-3.5 shrink-0 opacity-80 sm:block" />
            <p className="text-[12.5px] leading-snug">
              <span className="font-semibold">Public beta.</span>{" "}
              <span className="text-white/85">
                Answers are generated by AI and can be wrong, so check the cited
                sources before you rely on one.
              </span>
            </p>
          </div>
          <button
            onClick={dismiss}
            aria-label="Dismiss beta notice"
            className="absolute right-2 top-1/2 -translate-y-1/2 rounded-md p-1.5 text-white/70 transition-colors hover:bg-white/15 hover:text-white"
          >
            <X className="h-3.5 w-3.5" />
          </button>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
